// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdD1pJocUaGvCPPMdJWVtGbsB6mRqBut8',
    appId: '1:961243009208:web:6fabe41d6afd49deb7e44d',
    messagingSenderId: '961243009208',
    projectId: 'project-mob-49634',
    authDomain: 'project-mob-49634.firebaseapp.com',
    storageBucket: 'project-mob-49634.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoRtMFbjeQrNbG8m1Egx36Y7NjAT22dac',
    appId: '1:961243009208:android:72a40e1daa4d96ffb7e44d',
    messagingSenderId: '961243009208',
    projectId: 'project-mob-49634',
    storageBucket: 'project-mob-49634.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuS5-PmXpvMQiDCiWPZWc4pZig1eaC2_I',
    appId: '1:961243009208:ios:9fff7769ee6bf2d1b7e44d',
    messagingSenderId: '961243009208',
    projectId: 'project-mob-49634',
    storageBucket: 'project-mob-49634.appspot.com',
    androidClientId: '961243009208-35hab6ukvf35ku90f3tjfpvamf457fjq.apps.googleusercontent.com',
    iosClientId: '961243009208-0k8akbh5dbgtusulqvgkp45rps9i7vk9.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectAppEateso',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuS5-PmXpvMQiDCiWPZWc4pZig1eaC2_I',
    appId: '1:961243009208:ios:9fff7769ee6bf2d1b7e44d',
    messagingSenderId: '961243009208',
    projectId: 'project-mob-49634',
    storageBucket: 'project-mob-49634.appspot.com',
    androidClientId: '961243009208-35hab6ukvf35ku90f3tjfpvamf457fjq.apps.googleusercontent.com',
    iosClientId: '961243009208-0k8akbh5dbgtusulqvgkp45rps9i7vk9.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectAppEateso',
  );
}
